version = 0.1
[prod.deploy.parameters]
stack_name = "kavak-ai-agent"
resolve_s3 = true
s3_prefix = "kavak-ai-agent"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
use_container = true
parameter_overrides = "Stage=\"prod\" TwilioPhoneNumber=\"+14155238886\" ModelName=\"gpt-4-turbo-preview\" Temperature=\"0.7\" MaxTokens=\"1000\""
image_repositories = []
