version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "kavak-ai-agent"
s3_bucket = "kavak-ai-agent-deployment-bucket"
s3_prefix = "kavak-ai-agent"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "Stage=dev,"
env_file = "env.json"
image_repositories = []

[default.build]
[default.build.parameters]
use_container = true

[default.local_start_api]
[default.local_start_api.parameters]
warm_containers = "EAGER"
parameter_overrides = "Stage=dev"
env_file = "env.json" 